In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.utils import to_categorical

# Load data from the CSV file
data = pd.read_csv("../Data/data.csv")

# Define the features and labels
X = data.iloc[:, :-1].values  # Features
y = data.iloc[:, -1].values    # Labels

# Perform one-hot encoding for the labels
y = to_categorical(y, num_classes=40)  # Assuming there are 40 possible activity classes (0 to 39)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Reshape the data for CNN (assuming a single channel for each feature)
X_train = X_train.reshape(-1, X_train.shape[1], 1, 1)
X_test = X_test.reshape(-1, X_test.shape[1], 1, 1)

# Define the CNN model
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 1), activation='relu', input_shape=(X_train.shape[1], 1, 1)))
model.add(MaxPooling2D(pool_size=(2, 1)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(40, activation='softmax'))  # 40 possible activity classes (0 to 39)

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=2, verbose=1)

# Evaluate the model on the training data
train_loss, train_accuracy = model.evaluate(X_train, y_train, verbose=0)
print(f'Training Accuracy: {train_accuracy * 100:.2f}%')


Epoch 1/50
428/428 [==============================] - 24s 6ms/step - loss: 3.5540 - accuracy: 0.1238
Epoch 2/50
428/428 [==============================] - 3s 7ms/step - loss: 2.6684 - accuracy: 0.1857
Epoch 3/50
428/428 [==============================] - 2s 5ms/step - loss: 2.4210 - accuracy: 0.2231
Epoch 4/50
428/428 [==============================] - 2s 4ms/step - loss: 2.3563 - accuracy: 0.2255
Epoch 5/50
428/428 [==============================] - 2s 4ms/step - loss: 2.2858 - accuracy: 0.2056
Epoch 6/50
428/428 [==============================] - 2s 4ms/step - loss: 2.2365 - accuracy: 0.2371
Epoch 7/50
428/428 [==============================] - 2s 4ms/step - loss: 2.2089 - accuracy: 0.2360
Epoch 8/50
428/428 [==============================] - 2s 4ms/step - loss: 2.1907 - accuracy: 0.2278
Epoch 9/50
428/428 [==============================] - 2s 4ms/step - loss: 2.1681 - accuracy: 0.2290
Epoch 10/50
428/428 [==============================] - 1s 3ms/step - loss: 2.1429 - accuracy: 0.239

In [3]:
# Save the trained model
model.save("model.h5")

In [4]:
# Make predictions on the training data
train_predictions = model.predict(X_train)

# Get the top 4 predicted classes based on class probabilities
top4_predicted_classes = np.argsort(train_predictions, axis=1)[:, -4:]

# Print the top 4 predicted classes for each sample
print("Top 4 Predicted Classes for Training Data:")
print(top4_predicted_classes)


27/27 [==============================] - 0s 4ms/step
Top 4 Predicted Classes for Training Data:
[[20 15 18 38]
 [24 23 11 25]
 [36 18 38 20]
 ...
 [ 8  5  7  6]
 [36 18 38 20]
 [35 32 31 33]]


In [5]:
X_train.shape

(856, 5, 1, 1)

In [6]:
# Load the saved model for predictions
loaded_model = tf.keras.models.load_model("model.h5")
predictions = loaded_model.predict(X_train[0])
# Get the top 4 predicted classes based on class probabilities
top4_predicted_classes = np.argsort(predictions, axis=1)[:, -4:]

print("Predicted Labels for New Input Data:")
print(top4_predicted_classes)

ValueError: in user code:

    File "c:\Users\mohan\anaconda3\lib\site-packages\keras\engine\training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "c:\Users\mohan\anaconda3\lib\site-packages\keras\engine\training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\mohan\anaconda3\lib\site-packages\keras\engine\training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "c:\Users\mohan\anaconda3\lib\site-packages\keras\engine\training.py", line 1983, in predict_step
        return self(x, training=False)
    File "c:\Users\mohan\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\mohan\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 5, 1, 1), found shape=(None, 1, 1)


In [5]:
# Convert the model to TensorFlow SavedModel format
tf.saved_model.save(model, './saved_model')

INFO:tensorflow:Assets written to: ./saved_model\assets


INFO:tensorflow:Assets written to: ./saved_model\assets


In [6]:
model.save('model')

INFO:tensorflow:Assets written to: model\assets


INFO:tensorflow:Assets written to: model\assets


In [8]:
X_train.shape[1]

5